<a href="https://colab.research.google.com/github/Sehaj-kahlon/Economic-Load-Dispatch/blob/main/ML-code/MinorProject_6Bus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/6Busdata.csv')

In [ ]:
df.sample(n=10, replace=True)

,P1,P2,P3,P4,P5,P6,Total Power,Power Loss,Power Demand,Total Cost(Rs/h)
103,305.6596,68.5396,153.5080,50.0000,53.1853,50.0000,680.8925,4.139538,676.753,8082.86
293,448.4196,173.9689,264.2765,139.9682,166.1901,105.6017,1298.4250,12.079000,1286.346,15751.41
108,310.5464,72.1645,157.2885,50.0000,57.0801,50.0000,697.0795,4.326505,692.753,8266.28
333,492.5765,200.0000,296.9810,150.0000,193.8567,120.0000,1453.4142,15.158200,1438.256,17851.21
116,319.8041,79.0321,164.4497,50.0000,64.4466,50.0000,727.7325,4.698503,723.034,8616.59
64,234.2500,50.0000,98.2130,50.0000,50.0000,50.0000,532.4630,2.460000,530.003,6475.49
283,442.3931,169.5178,259.5909,135.0301,161.4922,99.5247,1267.5488,11.653800,1255.895,15340.24
321,474.0811,193.5874,283.6766,150.0000,184.9886,120.0000,1406.3337,13.984700,1392.349,17205.88
269,425.0569,156.7135,246.1124,120.8370,147.9458,82.0675,1178.7331,10.479000,1168.254,14172.13
66,238.3110,50.0000,101.3300,50.0000,50.0000,50.0000,539.6410,2.531000,537.110,6549.43

In [ ]:
df.shape

(339, 10)

In [ ]:
df

,P1,P2,P3,P4,P5,P6,Total Power,Power Loss,Power Demand,Total Cost(Rs/h)
0,102.6430,50.0,80.0000,50.0,50.0000,50.0,382.6430,1.3870,381.256,5059.85
1,103.2540,50.0,80.0000,50.0,50.0000,50.0,383.2530,1.3890,381.864,5065.01
2,103.8450,50.0,80.0000,50.0,50.0000,50.0,383.8450,1.3930,382.452,5070.00
3,104.3390,50.0,80.0000,50.0,50.0000,50.0,384.3390,1.3950,382.944,5074.18
4,104.4380,50.0,80.0000,50.0,50.0000,50.0,384.4380,1.3950,383.043,5075.02
...,...,...,...,...,...,...,...,...,...,...
334,494.2673,200.0,298.2785,150.0,195.1107,120.0,1457.6565,15.2735,1442.383,17909.78
335,495.9876,200.0,299.5987,150.0,196.3861,120.0,1461.9724,15.3914,1446.581,17969.46
336,500.0000,200.0,300.0000,150.0,193.5370,120.0,1463.5370,14.3940,1449.143,18006.38
337,500.0000,200.0,300.0000,150.0,197.9143,120.0,1467.9143,15.5473,1452.367,18051.96
338,500.0000,200.0,300.0000,150.0,200.0000,120.0,1470.0000,14.7120,1455.288,18080.50

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   P1                339 non-null    float64
 1   P2                339 non-null    float64
 2   P3                339 non-null    float64
 3   P4                339 non-null    float64
 4   P5                339 non-null    float64
 5   P6                339 non-null    float64
 6   Total Power       339 non-null    float64
 7   Power Loss        339 non-null    float64
 8   Power Demand      339 non-null    float64
 9   Total Cost(Rs/h)  339 non-null    float64
dtypes: float64(10)
memory usage: 26.6 KB

In [ ]:
df.describe()

,P1,P2,P3,P4,P5,P6,Total Power,Power Loss,Power Demand,Total Cost(Rs/h)
count,339.000000,339.000000,339.000000,339.000000,339.000000,339.000000,339.000000,339.000000,339.000000,339.000000
mean,339.222427,111.659604,187.650667,85.002496,104.433877,65.163092,889.595832,7.760313,885.789601,10771.202419
std,107.327824,49.808710,68.163197,36.665589,48.522190,23.926117,323.621638,10.306349,317.030464,3842.720778
min,102.643000,50.000000,80.000000,50.000000,50.000000,50.000000,107.240500,1.387000,381.256000,5059.850000
25%,273.563750,50.000000,128.353050,50.000000,50.000000,50.000000,599.959500,3.200069,598.716500,7208.075000
50%,365.885800,113.040800,199.991200,72.348100,101.342300,50.000000,899.278200,6.978139,895.700000,10687.950000
75%,413.370000,148.081700,237.026400,111.279100,138.786600,70.319450,1116.515950,9.771650,1109.135500,13396.995000
max,500.000000,200.000000,300.000000,150.000000,291.495800,120.000000,1538.421300,142.912800,1455.288000,18080.500000

In [ ]:
from sklearn.tree import DecisionTreeRegressor
# create datasets
X=df.iloc[:,8]
y=df.iloc[:,[0,1,2,3,4,5,7,9]]
print(X)

0       381.256
1       381.864
2       382.452
3       382.944
4       383.043
         ...
334    1442.383
335    1446.581
336    1449.143
337    1452.367
338    1455.288
Name: Power Demand, Length: 339, dtype: float64

In [ ]:
Xf=X.values.reshape(-1, 1)

In [ ]:
print(Xf)

[[ 381.256 ]
 [ 381.864 ]
 [ 382.452 ]
 [ 382.944 ]
 [ 383.043 ]
 [ 383.772 ]
 [ 384.165 ]
 [ 384.658 ]
 [ 385.105 ]
 [ 385.749 ]
 [ 386.083 ]
 [ 386.548 ]
 [ 387.064 ]
 [ 387.815 ]
 [ 388.359 ]
 [ 388.994 ]
 [ 390.523 ]
 [ 392.156 ]
 [ 394.456 ]
 [ 396.281 ]
 [ 399.781 ]
 [ 402.482 ]
 [ 405.684 ]
 [ 407.982 ]
 [ 409.821 ]
 [ 412.671 ]
 [ 415.213 ]
 [ 418.551 ]
 [ 420.223 ]
 [ 422.891 ]
 [ 425.678 ]
 [ 428.974 ]
 [ 430.561 ]
 [ 433.789 ]
 [ 436.11  ]
 [ 439.005 ]
 [ 441.223 ]
 [ 443.255 ]
 [ 446.556 ]
 [ 449.468 ]
 [ 451.945 ]
 [ 453.674 ]
 [ 455.98  ]
 [ 458.231 ]
 [ 461.023 ]
 [ 464.482 ]
 [ 468.331 ]
 [ 472.446 ]
 [ 475.334 ]
 [ 478.662 ]
 [ 482.552 ]
 [ 486.984 ]
 [ 488.941 ]
 [ 491.331 ]
 [ 493.554 ]
 [ 497.776 ]
 [ 501.244 ]
 [ 505.642 ]
 [ 509.691 ]
 [ 513.345 ]
 [ 517.456 ]
 [ 519.56  ]
 [ 522.223 ]
 [ 526.331 ]
 [ 530.003 ]
 [ 533.455 ]
 [ 537.11  ]
 [ 543.434 ]
 [ 547.894 ]
 [ 550.511 ]
 [ 553.356 ]
 [ 558.844 ]
 [ 561.112 ]
 [ 563.223 ]
 [ 567.008 ]
 [ 568.899 ]
 [ 572.228 ]
 [ 576.665 ]
 [ 577.488 ]
 [ 580.808 ]
 [ 583.336 ]
 [ 587.774 ]
 [ 591.456 ]
 [ 595.452 ]
 [ 598.112 ]
 [ 599.321 ]
 [ 602.345 ]
 [ 607.321 ]
 [ 609.003 ]
 [ 615.723 ]
 [ 618.834 ]
 [ 621.721 ]
 [ 624.904 ]
 [ 628.643 ]
 [ 631.682 ]
 [ 635.721 ]
 [ 640.099 ]
 [ 646.55  ]
 [ 651.745 ]
 [ 658.952 ]
 [ 662.944 ]
 [ 667.234 ]
 [ 671.888 ]
 [ 676.753 ]
 [ 679.005 ]
 [ 682.533 ]
 [ 685.772 ]
 [ 690.237 ]
 [ 692.753 ]
 [ 698.271 ]
 [ 700.351 ]
 [ 705.002 ]
 [ 708.135 ]
 [ 711.722 ]
 [ 715.002 ]
 [ 720.612 ]
 [ 723.034 ]
 [ 728.281 ]
 [ 730.724 ]
 [ 735.712 ]
 [ 740.13  ]
 [ 742.812 ]
 [ 747.963 ]
 [ 752.712 ]
 [ 755.729 ]
 [ 760.923 ]
 [ 762.813 ]
 [ 768.024 ]
 [ 770.912 ]
 [ 775.823 ]
 [ 778.923 ]
 [ 780.812 ]
 [ 783.824 ]
 [ 789.635 ]
 [ 792.812 ]
 [ 795.923 ]
 [ 798.012 ]
 [ 802.612 ]
 [ 806.823 ]
 [ 809.735 ]
 [ 813.835 ]
 [ 817.634 ]
 [ 818.202 ]
 [ 820.455 ]
 [ 823.768 ]
 [ 826.909 ]
 [ 827.991 ]
 [ 830.337 ]
 [ 833.234 ]
 [ 836.985 ]
 [ 839.608 ]
 [ 841.372 ]
 [ 845.756 ]
 [ 848.974 ]
 [ 850.866 ]
 [ 853.899 ]
 [ 856.    ]
 [ 859.241 ]
 [ 862.212 ]
 [ 865.403 ]
 [ 868.89  ]
 [ 871.256 ]
 [ 874.508 ]
 [ 877.002 ]
 [ 880.438 ]
 [ 883.115 ]
 [ 886.984 ]
 [ 889.089 ]
 [ 892.414 ]
 [ 895.7   ]
 [ 900.875 ]
 [ 905.667 ]
 [ 908.542 ]
 [ 915.764 ]
 [ 918.357 ]
 [ 920.877 ]
 [ 923.345 ]
 [ 928.065 ]
 [ 935.837 ]
 [ 940.825 ]
 [ 948.997 ]
 [ 950.833 ]
 [ 955.837 ]
 [ 958.278 ]
 [ 960.89  ]
 [ 965.234 ]
 [ 970.357 ]
 [ 975.2346]
 [ 980.648 ]
 [ 982.667 ]
 [ 986.274 ]
 [ 990.565 ]
 [ 993.652 ]
 [ 998.936 ]
 [1010.789 ]
 [1015.899 ]
 [1020.732 ]
 [1025.467 ]
 [1027.89  ]
 [1030.006 ]
 [1037.101 ]
 [1037.562 ]
 [1038.412 ]
 [1038.987 ]
 [1039.102 ]
 [1039.894 ]
 [1040.214 ]
 [1040.456 ]
 [1041.254 ]
 [1042.223 ]
 [1042.566 ]
 [1042.854 ]
 [1043.256 ]
 [1044.152 ]
 [1045.785 ]
 [1046.456 ]
 [1047.21  ]
 [1048.247 ]
 [1048.299 ]
 [1049.541 ]
 [1050.278 ]
 [1051.781 ]
 [1052.478 ]
 [1053.41  ]
 [1054.815 ]
 [1055.784 ]
 [1056.124 ]
 [1058.142 ]
 [1060.178 ]
 [1062.478 ]
 [1063.147 ]
 [1065.214 ]
 [1068.145 ]
 [1069.214 ]
 [1070.541 ]
 [1075.127 ]
 [1078.457 ]
 [1079.541 ]
 [1080.214 ]
 [1081.241 ]
 [1082.147 ]
 [1083.114 ]
 [1085.214 ]
 [1086.147 ]
 [1087.368 ]
 [1089.147 ]
 [1090.48  ]
 [1094.287 ]
 [1095.248 ]
 [1098.458 ]
 [1098.998 ]
 [1100.101 ]
 [1105.487 ]
 [1108.147 ]
 [1110.124 ]
 [1115.214 ]
 [1118.187 ]
 [1120.847 ]
 [1125.68  ]
 [1128.157 ]
 [1130.217 ]
 [1135.147 ]
 [1140.658 ]
 [1145.235 ]
 [1152.356 ]
 [1153.224 ]
 [1155.214 ]
 [1159.214 ]
 [1160.214 ]
 [1168.254 ]
 [1172.478 ]
 [1173.257 ]
 [1178.147 ]
 [1179.541 ]
 [1180.547 ]
 [1189.214 ]
 [1195.147 ]
 [1215.357 ]
 [1218.159 ]
 [1225.147 ]
 [1236.017 ]
 [1240.59  ]
 [1250.587 ]
 [1255.895 ]
 [1256.871 ]
 [1259.271 ]
 [1262.006 ]
 [1266.458 ]
 [1269.587 ]
 [1272.369 ]
 [1275.128 ]
 [1279.589 ]
 [1283.621 ]
 [1286.346 ]
 [1290.287 ]
 [1292.367 ]
 [1294.553 ]
 [1298.821 ]
 [1302.412 ]
 [1306.328 ]
 [1310.008 ]
 [1314.052 ]
 [1318.227 ]
 [1322.148 ]
 [1327.003 ]
 [1331.253 ]
 [1335.891 ]
 [1337.254 ]
 [1340.305 ]
 [1344.981 ]
 [1349.421 ]
 [1351.006 ]
 [1353.231 ]
 [1358.319 ]
 [1363.081 ]
 [1368.764 ]
 [1372.541 ]
 [1376.388 ]
 [1380.003 ]
 [1384.834 ]
 [1388.267 ]
 [1392.349 ]
 [1396.111 ]
 [1400.562 ]
 [1404.286 ]
 [1408.99  ]
 [1412.593 ]
 [1416.288 ]
 [1420.799 ]
 [1424.005 ]
 [1427.458 ]
 [1431.287 ]
 [1435.681 ]
 [1438.256 ]
 [1442.383 ]
 [1446.581 ]
 [1449.143 ]
 [1452.367 ]
 [1455.288 ]]

In [ ]:
print(y)

           P1     P2        P3     P4        P5     P6  Power Loss  \
0    102.6430   50.0   80.0000   50.0   50.0000   50.0      1.3870
1    103.2540   50.0   80.0000   50.0   50.0000   50.0      1.3890
2    103.8450   50.0   80.0000   50.0   50.0000   50.0      1.3930
3    104.3390   50.0   80.0000   50.0   50.0000   50.0      1.3950
4    104.4380   50.0   80.0000   50.0   50.0000   50.0      1.3950
..        ...    ...       ...    ...       ...    ...         ...
334  494.2673  200.0  298.2785  150.0  195.1107  120.0     15.2735
335  495.9876  200.0  299.5987  150.0  196.3861  120.0     15.3914
336  500.0000  200.0  300.0000  150.0  193.5370  120.0     14.3940
337  500.0000  200.0  300.0000  150.0  197.9143  120.0     15.5473
338  500.0000  200.0  300.0000  150.0  200.0000  120.0     14.7120

     Total Cost(Rs/h)
0             5059.85
1             5065.01
2             5070.00
3             5074.18
4             5075.02
..                ...
334          17909.78
335          17969.46
336          18006.38
337          18051.96
338          18080.50

[339 rows x 8 columns]

In [ ]:
# define model
model = DecisionTreeRegressor()

# fit model
model.fit(Xf, y)

# make a prediction
row=[900]
yhat = model.predict([row])

# summarize prediction
print(yhat)

[[3.671617e+02 1.139850e+02 2.009762e+02 7.337720e+01 1.023530e+02
  5.000000e+01 6.978139e+00 1.075176e+04]]

In [ ]:
print(yhat)

[[3.173474e+02 7.720950e+01 1.625494e+02 5.000000e+01 6.249320e+01
  5.000000e+01 4.597516e+00 8.523270e+03]]

In [ ]:
yhat.shape

(1, 8)

In [ ]:
p1=yhat[0][0]
p2=yhat[0][1]
p3=yhat[0][2]
p4=yhat[0][3]
p5=yhat[0][4]
p6=yhat[0][5]
cost=yhat[0][7]
ptotal=p1+p2+p3+p4+p5+p6
ploss=yhat[0][6]
print("P1=",p1,"\nP2=",p2,"\nP3=",p3,"\nP4=",p4,"\nP5=",p5,"\nP6=",p6,"\nTotal Power=",ptotal,"\nPower Loss=",ploss,"\nTotal Cost= ",cost)

P1= 367.1617
P2= 113.985
P3= 200.9762
P4= 73.3772
P5= 102.353
P6= 50.0
Total Power= 907.8531
Power Loss= 6.978139
Total Cost=  10751.76